/* ============================================================
   CodeMap — PRE-CACHED graph (auto-generated by scripts/precache.mjs).

   A REAL Gemini-generated architecture map for brul30/getCovered.
   Guarantees a working demo even if live /api/analyze fails: /map prefers
   the live sessionStorage graph → this → the seed (lib/data.ts).

   DO NOT EDIT BY HAND — re-run: node --env-file=.env.local scripts/precache.mjs
   ============================================================ */
import type { CodeMapGraph } from "./data";

export const PRECACHED: CodeMapGraph = {
  "repo": {
    "owner": "brul30",
    "name": "getCovered",
    "branch": "main",
    "commit": "2669a2f"
  },
  "stage": {
    "w": 938,
    "h": 930
  },
  "nodes": [
    {
      "id": "user-portal",
      "label": "User Portal",
      "kind": "frontend",
      "sub": "Next.js & Tailwind CSS",
      "icon": "browser",
      "summary": "The interactive web interface where renters upload their insurance policies and reviewers examine, edit, and approve or deny submissions.",
      "tech": "Next.js, React 19, Tailwind CSS v4",
      "files": [
        {
          "name": "app/renter/RenterDashboard.tsx",
          "loc": "150 LOC",
          "cov": 0.9
        },
        {
          "name": "app/reviewer/ReviewerWorkspace.tsx",
          "loc": "180 LOC",
          "cov": 0.9
        },
        {
          "name": "app/login/LoginForm.tsx",
          "loc": "80 LOC",
          "cov": 0.9
        }
      ],
      "narration": "This is the website that renters and reviewers interact with. Renters can easily drag and drop their insurance documents here, while reviewers get a split-screen console to verify details.",
      "x": 318,
      "y": 60,
      "w": 240,
      "selectedDefault": true
    },
    {
      "id": "server-gateways",
      "label": "Server Gateways & Actions",
      "kind": "layer",
      "sub": "Next.js Server Actions & Proxy",
      "icon": "route",
      "summary": "Handles secure user requests, manages active login sessions, and coordinates file uploads and reviewer decisions safely behind the scenes.",
      "tech": "Next.js Server Actions, TypeScript",
      "files": [
        {
          "name": "app/actions/submit.ts",
          "loc": "90 LOC",
          "cov": 0.95
        },
        {
          "name": "app/actions/decide.ts",
          "loc": "120 LOC",
          "cov": 0.95
        },
        {
          "name": "proxy.ts",
          "loc": "40 LOC",
          "cov": 0.9
        }
      ],
      "narration": "Think of this as the secure control room. It processes user actions like logging in, submitting files, and making final decisions, ensuring everything is verified before reaching the database.",
      "x": 638,
      "y": 290,
      "w": 240
    },
    {
      "id": "ai-extraction-engine",
      "label": "AI Extraction Engine",
      "kind": "service",
      "sub": "Next.js after() & Zod",
      "icon": "spark",
      "summary": "An asynchronous background worker that coordinates document download, pre-validation, and structured data extraction using AI.",
      "tech": "TypeScript, Zod, pdf-lib",
      "files": [
        {
          "name": "lib/extraction/extract.ts",
          "loc": "160 LOC",
          "cov": 0.95
        },
        {
          "name": "lib/validations/policy.ts",
          "loc": "140 LOC",
          "cov": 0.98
        },
        {
          "name": "lib/validations/file.ts",
          "loc": "80 LOC",
          "cov": 0.95
        }
      ],
      "narration": "Once a file is uploaded, this engine immediately takes over in the background. It reads the document, runs safety checks, and prepares the data for the AI to analyze.",
      "x": 555,
      "y": 520,
      "w": 240
    },
    {
      "id": "gemini-api",
      "label": "Google Gemini AI",
      "kind": "external",
      "sub": "Gemini 2.5 Flash REST API",
      "icon": "cpu",
      "summary": "External artificial intelligence service used to read uploaded documents and extract structured insurance fields like coverage amounts and dates.",
      "tech": "Google Gemini 2.5 Flash",
      "files": [
        {
          "name": "lib/extraction/gemini.ts",
          "loc": "110 LOC",
          "cov": 0.92
        }
      ],
      "narration": "This is the external brain. We securely send the policy documents to Google's Gemini AI, which reads the text and extracts key details like the insurance company, policyholder name, and coverage limits.",
      "x": 60,
      "y": 750,
      "w": 240
    },
    {
      "id": "supabase-db",
      "label": "Supabase Database",
      "kind": "service",
      "sub": "PostgreSQL & Row-Level Security",
      "icon": "database",
      "summary": "A secure cloud database storing user profiles and policy submissions, protected by strict database-level access rules (RLS).",
      "tech": "PostgreSQL, Supabase Auth",
      "files": [
        {
          "name": "supabase/migrations/20260529120000_init_schema.sql",
          "loc": "150 LOC",
          "cov": 1
        },
        {
          "name": "supabase/migrations/20260529120100_auth_rls.sql",
          "loc": "120 LOC",
          "cov": 1
        },
        {
          "name": "supabase/migrations/20260529120300_decision_guard.sql",
          "loc": "80 LOC",
          "cov": 1
        }
      ],
      "children": [
        {
          "name": "profiles",
          "type": "table",
          "meta": "Stores user accounts and roles"
        },
        {
          "name": "submissions",
          "type": "table",
          "meta": "Stores policies, AI extractions, and decisions"
        }
      ],
      "narration": "This is our secure vault. It stores all user profiles and policy submissions. It has built-in security rules that guarantee renters can only see their own files, while reviewers can see everything.",
      "x": 555,
      "y": 750,
      "w": 240
    },
    {
      "id": "secure-storage",
      "label": "Secure Storage Bucket",
      "kind": "service",
      "sub": "Supabase Storage",
      "icon": "bucket",
      "summary": "Private storage bucket that holds uploaded policy PDFs and images, accessible only via short-lived, secure signed links.",
      "tech": "Supabase Storage",
      "files": [
        {
          "name": "supabase/migrations/20260529120200_storage.sql",
          "loc": "60 LOC",
          "cov": 1
        },
        {
          "name": "app/actions/document.ts",
          "loc": "50 LOC",
          "cov": 0.9
        }
      ],
      "children": [
        {
          "name": "policy-documents",
          "type": "bucket",
          "meta": "Private folder for uploaded policy files"
        }
      ],
      "narration": "All uploaded insurance documents are saved in this highly secure digital filing cabinet. Files are private by default, and we only generate temporary, 60-second links when a renter or reviewer needs to view them.",
      "x": 245,
      "y": 520,
      "w": 240
    }
  ],
  "edges": [
    {
      "from": "user-portal",
      "to": "server-gateways",
      "label": "Sends actions"
    },
    {
      "from": "server-gateways",
      "to": "secure-storage",
      "label": "Uploads files"
    },
    {
      "from": "server-gateways",
      "to": "supabase-db",
      "label": "Saves records"
    },
    {
      "from": "server-gateways",
      "to": "ai-extraction-engine",
      "label": "Triggers background"
    },
    {
      "from": "ai-extraction-engine",
      "to": "gemini-api",
      "label": "Requests extraction"
    },
    {
      "from": "ai-extraction-engine",
      "to": "supabase-db",
      "label": "Updates results"
    },
    {
      "from": "supabase-db",
      "to": "user-portal",
      "label": "Realtime updates"
    },
    {
      "from": "user-portal",
      "to": "secure-storage",
      "label": "Fetches document"
    }
  ],
  "kinds": {
    "frontend": {
      "label": "Frontend",
      "sw": "#7aa2ff"
    },
    "layer": {
      "label": "App layer",
      "sw": "#3ee0c4"
    },
    "service": {
      "label": "Service",
      "sw": "#c792ea"
    },
    "external": {
      "label": "External",
      "sw": "#ffb86b"
    }
  },
  "voiceScript": [
    {
      "query": "How does the user portal work?",
      "node": "user-portal"
    },
    {
      "query": "How does the server gateways & actions work?",
      "node": "server-gateways"
    },
    {
      "query": "How does the ai extraction engine work?",
      "node": "ai-extraction-engine"
    },
    {
      "query": "How does the google gemini ai work?",
      "node": "gemini-api"
    },
    {
      "query": "How does the supabase database work?",
      "node": "supabase-db"
    }
  ],
  "logSeed": [
    {
      "tag": "system",
      "msg": "Repository <span class='hl'>brul30/getCovered</span> cloned · 6 components"
    },
    {
      "tag": "agent",
      "msg": "Walking tree · branch <span class='hl'>main</span> @ 2669a2f"
    },
    {
      "tag": "ok",
      "msg": "Gemini emitted map · <span class='hl'>6</span> nodes · 8 edges"
    }
  ],
  "logStream": [
    {
      "tag": "agent",
      "msg": "Watching <span class='hl'>main</span> · no drift since 2669a2f"
    },
    {
      "tag": "ok",
      "msg": "Analysis complete · project status → <span class='hl'>ready</span>"
    },
    {
      "tag": "voice",
      "msg": "Voice layer armed · say \"show me the user portal\""
    }
  ]
};

export default PRECACHED;
